#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Clustering and token manipulation utilities for visual token models.

This module provides clustering, token transformation, and visualization
functions for working with visual tokens in transformer-based models.
"""

import logging
import re
import math
import warnings
import torch
import torch.nn.functional as F
import torch.nn as nn

logger = logging.getLogger(__name__)


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    """
    Truncated normal distribution initialization without gradient tracking.
    
    Based on: https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    
    Args:
        tensor: tensor to initialize
        mean: mean of the distribution
        std: standard deviation of the distribution
        a: minimum cut-off value
        b: maximum cut-off value
    
    Returns:
        Initialized tensor
    """
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    """
    Fills the input Tensor with values drawn from a truncated normal distribution.
    
    Args:
        tensor: an n-dimensional torch.Tensor
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    
    Returns:
        Initialized tensor
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def drop_path(x, drop_prob=0., training=False):
    """
    Drop paths (Stochastic Depth) per sample when applied in main path of residual blocks.
    
    Args:
        x: input tensor
        drop_prob: probability of dropping the path
        training: whether in training mode
    
    Returns:
        Output after applying drop path
    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output


class DropPath(nn.Module):
    """
    Drop paths (Stochastic Depth) per sample when applied in main path of residual blocks.
    
    Args:
        drop_prob: probability of dropping the path
    """
    def __init__(self, drop_prob=None):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training)


def get_grid_index(init_size, map_size, device):
    """
    For each initial grid, get its index in the feature map.
    
    Args:
        init_size: initial grid resolution [H_init, W_init]
        map_size: feature map resolution [H, W]
        device: computation device
    
    Returns:
        idx: index in flattened feature map
    """
    H_init, W_init = init_size
    H, W = map_size
    idx = torch.arange(H * W, device=device).reshape(1, 1, H, W)
    idx = F.interpolate(idx.float(), [H_init, W_init], mode='nearest').long()
    return idx.flatten()


def index_points(points, idx):
    """
    Sample features following the index.
    
    Args:
        points: input points data [B, N, C]
        idx: sample index data [B, S]
    
    Returns:
        indexed points data [B, S, C]
    """
    device = points.device
    B = points.shape[0]
    view_shape = list(idx.shape)
    view_shape[1:] = [1] * (len(view_shape) - 1)
    repeat_shape = list(idx.shape)
    repeat_shape[0] = 1
    batch_indices = torch.arange(B, dtype=torch.long).to(device).view(view_shape).repeat(repeat_shape)
    new_points = points[batch_indices, idx, :]
    return new_points


def token2map(token_dict):
    """
    Transform vision tokens to feature map.
    
    This function works when the resolution of the feature map is not higher
    than the initial grid structure.
    
    Args:
        token_dict: dictionary containing token information
    
    Returns:
        Feature map tensor [B, C, H, W]
    """
    x = token_dict['x']
    H, W = token_dict['map_size']
    H_init, W_init = token_dict['init_grid_size']
    idx_token = token_dict['idx_token']
    B, N, C = x.shape
    N_init = H_init * W_init
    device = x.device

    if N_init == N and N == H * W:
        # For initial tokens with grid structure, just reshape
        return x.reshape(B, H, W, C).permute(0, 3, 1, 2).contiguous()

    # For each initial grid, get the corresponding index in
    # the flattened feature map
    idx_hw = get_grid_index(
        [H_init, W_init], [H, W], device=device)[None, :].expand(B, -1)
    idx_batch = torch.arange(B, device=device)[:, None].expand(B, N_init)
    value = x.new_ones(B * N_init)

    # Choose the way with fewer flops
    if N_init < N * H * W:
        # Use sparse matrix multiplication
        # Flops: B * N_init * (C+2)
        idx_hw = idx_hw + idx_batch * H * W
        idx_tokens = idx_token + idx_batch * N
        coor = torch.stack([idx_hw, idx_tokens], dim=0).reshape(2, B * N_init)

        # torch.sparse does not support fp16
        with torch.cuda.amp.autocast(enabled=False):
            # torch.sparse does not support gradient for
            # sparse tensor, so we detach it
            value = value.detach().float()

            # Build a sparse matrix with shape [B * H * W, B * N]
            A = torch.sparse.FloatTensor(coor, value, torch.Size([B * H * W, B * N]))

            # Normalize the weight for each row
            all_weight = A @ x.new_ones(B * N, 1).type(torch.float32) + 1e-6
            value = value / all_weight[idx_hw.reshape(-1), 0]

            # Update the matrix with normalized weight
            A = torch.sparse.FloatTensor(coor, value, torch.Size([B * H * W, B * N]))

            # Sparse matrix multiplication
            x_out = A @ x.reshape(B * N, C).type(torch.float32)  # [B*H*W, C]

    else:
        # Use dense matrix multiplication
        # Flops: B * N * H * W * (C+2)
        coor = torch.stack([idx_batch, idx_hw, idx_token], dim=0).reshape(3, B * N_init)

        # Build a matrix with shape [B, H*W, N]
        A = torch.sparse.FloatTensor(coor, value, torch.Size([B, H * W, N])).to_dense()
        # Normalize the weight
        A = A / (A.sum(dim=-1, keepdim=True) + 1e-6)

        x_out = A @ x  # [B, H*W, C]

    x_out = x_out.type(x.dtype)
    x_out = x_out.reshape(B, H, W, C).permute(0, 3, 1, 2).contiguous()
    return x_out


def map2token(feature_map, token_dict):
    """
    Transform feature map to vision tokens.
    
    Args:
        feature_map: feature map tensor [B, C, H, W]
        token_dict: dictionary containing token information
    
    Returns:
        Token features tensor [B, N, C]
    """
    idx_token = token_dict['idx_token']
    N = token_dict['token_num']
    H_init, W_init = token_dict['init_grid_size']
    N_init = H_init * W_init

    # We do not use the weight value here
    agg_weight = None

    B, C, H, W = feature_map.shape
    device = feature_map.device

    if N_init == N and N == H * W:
        # For initial tokens with grid structure, just reshape
        return feature_map.flatten(2).permute(0, 2, 1).contiguous()

    idx_hw = get_grid_index(
        [H_init, W_init], [H, W], device=device)[None, :].expand(B, -1)

    idx_batch = torch.arange(B, device=device)[:, None].expand(B, N_init)
    if agg_weight is None:
        value = feature_map.new_ones(B * N_init)
    else:
        value = agg_weight.reshape(B * N_init).type(feature_map.dtype)

    # Choose the way with fewer flops
    if N_init < N * H * W:
        # Use sparse matrix multiplication
        # Flops: B * N_init * (C+2)
        idx_token = idx_token + idx_batch * N
        idx_hw = idx_hw + idx_batch * H * W
        indices = torch.stack([idx_token, idx_hw], dim=0).reshape(2, -1)

        # torch.sparse does not support fp16
        with torch.cuda.amp.autocast(enabled=False):
            # Sparse mm does not support gradient for sparse matrix
            value = value.detach().float()
            # Build a sparse matrix with shape [B*N, B*H*W]
            A = torch.sparse_coo_tensor(indices, value, (B * N, B * H * W))
            # Normalize the matrix
            all_weight = A @ torch.ones(
                [B * H * W, 1], device=device, dtype=torch.float32) + 1e-6
            value = value / all_weight[idx_token.reshape(-1), 0]

            A = torch.sparse_coo_tensor(indices, value, (B * N, B * H * W))
            # out: [B*N, C]
            out = A @ feature_map.\
                permute(0, 2, 3, 1).contiguous().reshape(B * H * W, C).float()
    else:
        # Use dense matrix multiplication
        # Flops: B * N * H * W * (C+2)
        indices = torch.stack([idx_batch, idx_token, idx_hw], dim=0).reshape(3, -1)
        value = value.detach()  # To reduce training time, we detach here
        A = torch.sparse_coo_tensor(indices, value, (B, N, H * W)).to_dense()
        # Normalize the matrix
        A = A / (A.sum(dim=-1, keepdim=True) + 1e-6)

        out = A @ feature_map.permute(0, 2, 3, 1).reshape(B, H * W, C).contiguous()

    out = out.type(feature_map.dtype)
    out = out.reshape(B, N, C)
    return out


def token_downup(target_dict, source_dict):
    """
    Transform token features between different distributions.
    
    Args:
        target_dict: dictionary for target token information
        source_dict: dictionary for source token information
    
    Returns:
        Token features tensor [B, N, C]
    """
    x_s = source_dict['x']
    idx_token_s = source_dict['idx_token']
    idx_token_t = target_dict['idx_token']
    T = target_dict['token_num']
    B, S, C = x_s.shape
    N_init = idx_token_s.shape[1]

    weight = target_dict.get('agg_weight', None)
    if weight is None:
        weight = x_s.new_ones(B, N_init, 1)
    weight = weight.reshape(-1)

    # Choose the way with fewer flops
    if N_init < T * S:
        # Use sparse matrix multiplication
        # Flops: B * N_init * (C+2)
        idx_token_t = idx_token_t + torch.arange(B, device=x_s.device)[:, None] * T
        idx_token_s = idx_token_s + torch.arange(B, device=x_s.device)[:, None] * S
        coor = torch.stack([idx_token_t, idx_token_s], dim=0).reshape(2, B * N_init)

        # torch.sparse.spmm does not support fp16
        with torch.cuda.amp.autocast(enabled=False):
            # torch.sparse does not support grad for sparse matrix
            weight = weight.float().detach()
            # Build a matrix with shape [B*T, B*S]
            A = torch.sparse.FloatTensor(coor, weight, torch.Size([B * T, B * S]))
            # Normalize the matrix
            all_weight = A.type(torch.float32) @ x_s.new_ones(B * S, 1).type(torch.float32) + 1e-6
            weight = weight / all_weight[(idx_token_t).reshape(-1), 0]
            A = torch.sparse.FloatTensor(coor, weight, torch.Size([B * T, B * S]))
            # Sparse matmul
            x_out = A.type(torch.float32) @ x_s.reshape(B * S, C).type(torch.float32)
    else:
        # Use dense matrix multiplication
        # Flops: B * T * S * (C+2)
        idx_batch = torch.arange(B, device=x_s.device)[:, None].expand(B, N_init)
        coor = torch.stack([idx_batch, idx_token_t, idx_token_s], dim=0).reshape(3, B * N_init)
        weight = weight.detach()  # Detach to reduce training time
        # Build a matrix with shape [B, T, S]
        A = torch.sparse.FloatTensor(coor, weight, torch.Size([B, T, S])).to_dense()
        # Normalize the matrix
        A = A / (A.sum(dim=-1, keepdim=True) + 1e-6)
        # Dense matmul
        x_out = A @ x_s

    x_out = x_out.reshape(B, T, C).type(x_s.dtype)
    return x_out


def map2token_flops(N_init, C):
    """
    Calculate flops for map2token operation.
    
    Args:
        N_init: number of initial tokens
        C: channel dimension
    
    Returns:
        Estimated FLOPS count
    """
    return N_init * (2 + 1 + 1 + C)


def token2map_flops(N_init, C):
    """
    Calculate flops for token2map operation.
    
    Args:
        N_init: number of initial tokens
        C: channel dimension
    
    Returns:
        Estimated FLOPS count
    """
    return N_init * (2 + 1 + 1 + C)


def downup_flops(N_init, C):
    """
    Calculate flops for token_downup operation.
    
    Args:
        N_init: number of initial tokens
        C: channel dimension
    
    Returns:
        Estimated FLOPS count
    """
    return N_init * (2 + 1 + 1 + C)


def cluster_and_merge_flops(num_tokens, dim, k):
    """
    Calculate flops for cluster_dpc_knn and merge operations.
    
    Args:
        num_tokens: number of tokens
        dim: feature dimension
        k: k-nearest neighbors
    
    Returns:
        Estimated FLOPS count
    """
    flops = 0
    flops += num_tokens * num_tokens * dim  # Distance matrix
    flops += num_tokens * k                 # Local density
    flops += num_tokens * num_tokens        # Distance indicator
    flops += num_tokens * dim               # Token merge
    return flops


def sra_flops(h, w, r, dim):
    """
    Calculate flops for spatial reduction attention.
    
    Args:
        h: height
        w: width
        r: reduction ratio
        dim: feature dimension
    
    Returns:
        Estimated FLOPS count
    """
    return 2 * h * w * (h // r) * (w // r) * dim


def cluster_dpc_knn(token_dict, cluster_num, k=5, token_mask=None):
    """
    Cluster tokens with DPC-KNN algorithm.
    
    Args:
        token_dict: dictionary for token information
        cluster_num: number of clusters
        k: number of the nearest neighbors for local density
        token_mask: mask for valid tokens
    
    Returns:
        idx_cluster: cluster index for each token
        cluster_num: actual cluster number
    """
    with torch.no_grad():
        x = token_dict["x"]
        B, N, C = x.shape

        dist_matrix = torch.cdist(x, x) / (C ** 0.5)

        if token_mask is not None:
            token_mask = token_mask > 0
            # Make distance between empty tokens and any other tokens maximal
            dist_matrix = dist_matrix * token_mask[:, None, :] + \
                          (dist_matrix.max() + 1) * (~token_mask[:, None, :])

        # Get local density
        dist_nearest, index_nearest = torch.topk(dist_matrix, k=k, dim=-1, largest=False)
        density = (-(dist_nearest ** 2).mean(dim=-1)).exp()
        # Add noise to ensure no tokens have the same density
        density = density + torch.rand(
            density.shape, device=density.device, dtype=density.dtype) * 1e-6

        if token_mask is not None:
            # The density of empty token should be 0
            density = density * token_mask

        # Get distance indicator
        mask = density[:, None, :] > density[:, :, None]
        mask = mask.type(x.dtype)
        dist_max = dist_matrix.flatten(1).max(dim=-1)[0][:, None, None]
        dist, index_parent = (dist_matrix * mask + dist_max * (1 - mask)).min(dim=-1)

        # Select clustering center according to score
        score = dist * density
        _, index_down = torch.topk(score, k=cluster_num, dim=-1)

        # Assign tokens to the nearest center
        dist_matrix = index_points(dist_matrix, index_down)
        idx_cluster = dist_matrix.argmin(dim=1)

        # Make sure cluster center merges to itself
        idx_batch = torch.arange(B, device=x.device)[:, None].expand(B, cluster_num)
        idx_tmp = torch.arange(cluster_num, device=x.device)[None, :].expand(B, cluster_num)
        idx_cluster[idx_batch.reshape(-1), index_down.reshape(-1)] = idx_tmp.reshape(-1)

    return idx_cluster, cluster_num


def merge_tokens(token_dict, idx_cluster, cluster_num, token_weight=None):
    """
    Merge tokens in the same cluster to a single cluster.
    
    Args:
        token_dict: dictionary for input token information
        idx_cluster: cluster index for each token
        cluster_num: number of clusters
        token_weight: weight for each token
    
    Returns:
        Dictionary for output token information
    """
    x = token_dict['x']
    idx_token = token_dict['idx_token']
    agg_weight = token_dict['agg_weight']

    B, N, C = x.shape
    if token_weight is None:
        token_weight = x.new_ones(B, N, 1)

    idx_batch = torch.arange(B, device=x.device)[:, None]
    idx = idx_cluster + idx_batch * cluster_num

    all_weight = token_weight.new_zeros(B * cluster_num, 1)
    all_weight.index_add_(dim=0, index=idx.reshape(B * N),
                          source=token_weight.reshape(B * N, 1))
    all_weight = all_weight + 1e-6
    norm_weight = token_weight / all_weight[idx]

    # Average token features
    x_merged = x.new_zeros(B * cluster_num, C)
    source = x * norm_weight
    x_merged.index_add_(dim=0, index=idx.reshape(B * N),
                        source=source.reshape(B * N, C).type(x.dtype))
    x_merged = x_merged.reshape(B, cluster_num, C)

    idx_token_new = index_points(idx_cluster[..., None], idx_token).squeeze(-1)
    weight_t = index_points(norm_weight, idx_token)
    agg_weight_new = agg_weight * weight_t
    agg_weight_new = agg_weight_new / agg_weight_new.max(dim=1, keepdim=True)[0]

    out_dict = {
        'x': x_merged,
        'token_num': cluster_num,
        'idx_token': idx_token_new,
        'agg_weight': agg_weight_new,
        'mask': None
    }
    return out_dict


def vis_tokens(img, token_dict, edge_color=[1.0, 1.0, 1.0], edge_width=1):
    """
    Visualize tokens on the image.
    
    Args:
        img: input image tensor [B, 3, H, W]
        token_dict: dictionary for input token information
        edge_color: color for edges
        edge_width: width for edges
    
    Returns:
        Visualization image tensor [B, 3, H, W]
    """
    N = token_dict['token_num']
    device, dtype = img.device, img.dtype

    color_map = F.avg_pool2d(img, kernel_size=4)
    B, C, H, W = color_map.shape

    token_color = map2token(color_map, token_dict)
    tmp_dict = token_dict.copy()
    tmp_dict['map_size'] = [H, W]
    tmp_dict['x'] = token_color
    vis_img = token2map(tmp_dict)

    token_idx = torch.arange(N, device=device)[None, :, None].float() / N
    tmp_dict['x'] = token_idx
    idx_map = token2map(tmp_dict)  # [B, 1, H, W]

    vis_img = F.interpolate(vis_img, [H * 8, W * 8], mode='nearest')
    idx_map = F.interpolate(idx_map, [H * 8, W * 8], mode='nearest')

    kernel = idx_map.new_zeros([4, 1, 3, 3])
    kernel[:, :, 1, 1] = 1
    kernel[0, :, 0, 1] = -1
    kernel[1, :, 2, 1] = -1
    kernel[2, :, 1, 0] = -1
    kernel[3, :, 1, 2] = -1

    for i in range(edge_width):
        edge_map = F.conv2d(F.pad(idx_map, [1, 1, 1, 1], mode='replicate'), kernel)
        edge_map = (edge_map != 0).max(dim=1, keepdim=True)[0]
        idx_map = idx_map * (~edge_map) + torch.rand(idx_map.shape, device=device, dtype=dtype) * edge_map

    edge_color = torch.tensor(edge_color, device=device, dtype=dtype)[None, :, None, None]
    vis_img = vis_img * (~edge_map) + edge_color * edge_map
    return vis_img


def get_token_density_map(token_dict):
    """
    Get token density map.
    
    Args:
        token_dict: dictionary for token information
    
    Returns:
        Density map tensor [B, 1, H, W]
    """
    N = token_dict['token_num']
    idx_token = token_dict['idx_token']
    B, N_init = idx_token.shape
    device = idx_token.device
    idx_batch = torch.arange(B, device=device)[:, None].expand(B, N_init)

    coor = torch.stack([idx_batch, idx_token], dim=0).reshape(2, B * N_init)
    tmp = torch.ones(B * N_init, device=device)
    token_density = 1 / torch.sparse.FloatTensor(coor, tmp, torch.Size([B, N])).to_dense()
    tmp_dict = token_dict.copy()
    tmp_dict['x'] = token_density[..., None]
    density_map = token2map(tmp_dict)
    return density_map


class TokenConv(nn.Module):
    """
    Token convolution module.
    
    Args:
        in_channels: input channel dimension
        out_channels: output channel dimension
        kernel_size: convolution kernel size
        bias: whether to use bias
        padding: padding size
    """
    def __init__(self, in_channels, out_channels, kernel_size=1, bias=False, padding=0):
        super().__init__()
        self.conv = nn.Conv1d(in_channels=in_channels,
                              out_channels=out_channels,
                              kernel_size=kernel_size, bias=bias,
                              padding=padding)

    def forward(self, x):
        """
        Apply token convolution.
        
        Args:
            x: input token features [B, N, C]
        
        Returns:
            Output token features [B, N, C]
        """
        x = x + self.conv(x.permute(0, 2, 1)).permute(0, 2, 1)
        return x


class CTM(nn.Module):
    """
    Clustering Token Mixer module.
    
    Args:
        sample_ratio: token sampling ratio
        embed_dim: embedding dimension
        dim_out: output dimension
        k: k-nearest neighbors for clustering
    """
    def __init__(self, sample_ratio, embed_dim, dim_out, k=5):
        super().__init__()
        self.sample_ratio = sample_ratio
        self.dim_out = dim_out
        self.conv = TokenConv(in_channels=embed_dim, out_channels=dim_out, kernel_size=3, bias=False, padding=1)
        self.norm = nn.LayerNorm(self.dim_out)
        self.score = nn.Linear(self.dim_out, 1)
        self.k = k

    def forward(self, token_dict):
        """
        Apply Clustering Token Mixer.
        
        Args:
            token_dict: dictionary for token information
        
        Returns:
            Tuple of down_dict and token_dict
        """
        x = token_dict["x"]
        x = self.conv(x)
        x = self.norm(x)
        token_score = self.score(x)
        token_weight = token_score.squeeze(2)
        if token_dict["mask"] is not None:
            token_weight.masked_fill_((1 - token_dict["mask"]).to(torch.bool), float("-inf"))
        token_weight = token_weight.unsqueeze(2).exp()

        token_dict['x'] = x
        B, N, C = x.shape
        token_dict['token_score'] = token_score

        cluster_num = max(math.ceil(N * self.sample_ratio), 1)
        idx_cluster, cluster_num = cluster_dpc_knn(
            token_dict, cluster_num, self.k, token_mask=token_dict["mask"])

        down_dict = merge_tokens(token_dict, idx_cluster, cluster_num, token_weight)
        return down_dict, token_dict


class TCMlp(nn.Module):
    """
    MLP for dynamic tokens.
    
    Args:
        in_features: input feature dimension
        hidden_features: hidden feature dimension
        out_features: output feature dimension
        act_layer: activation layer
        drop: dropout rate
    """
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0.):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.dwconv = TokenConv(in_channels=hidden_features,
                                out_channels=hidden_features,
                                kernel_size=3, padding=1,
                                bias=True)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)
        self.apply(self._init_weights)

    def _init_weights(self, m):
        """Initialize weights for the module."""
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()

    def forward(self, token_dict):
        """
        Apply MLP to token features.
        
        Args:
            token_dict: dictionary containing token information
            
        Returns:
            Processed features
        """
        token_dict['x'] = self.fc1(token_dict['x'])
        x = self.dwconv(token_dict['x'])
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x


class TCAttention(nn.Module):
    """
    Attention module for dynamic tokens.
    
    Args:
        dim: feature dimension
        num_heads: number of attention heads
        qkv_bias: whether to use bias for qkv projection
        qk_scale: scale factor for qk attention
        attn_drop: dropout rate for attention
        proj_drop: dropout rate for projection
        sr_ratio: spatial reduction ratio
        use_sr_layer: whether to use spatial reduction layer
    """
    def __init__(self, dim, num_heads=8, qkv_bias=False, qk_scale=None, 
                 attn_drop=0., proj_drop=0., sr_ratio=1, use_sr_layer=True):
        super().__init__()
        assert dim % num_heads == 0, f"dim {dim} should be divided by num_heads {num_heads}."

        self.dim = dim
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = qk_scale or head_dim ** -0.5

        self.q = nn.Linear(dim, dim, bias=qkv_bias)
        self.kv = nn.Linear(dim, dim * 2, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)

        self.sr_ratio = sr_ratio
        self.use_sr_layer = use_sr_layer
        if sr_ratio > 1:
            if self.use_sr_layer:
                self.sr = nn.Conv2d(dim, dim, kernel_size=sr_ratio, stride=sr_ratio)
                self.norm = nn.LayerNorm(dim)
        self.apply(self._init_weights)

    def _init_weights(self, m):
        """Initialize weights for the module."""
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()

    def forward(self, q_dict, kv_dict):
        """
        Apply attention between token features.
        
        Args:
            q_dict: dictionary containing query token information
            kv_dict: dictionary containing key/value token information
            
        Returns:
            Attention output features
        """
        q = q_dict['x']
        kv = kv_dict['x']
        B, Nq, C = q.shape
        Nkv = kv.shape[1]
        conf_kv = kv_dict.get('token_score', kv.new_zeros(B, Nkv, 1))

        q = self.q(q).reshape(B, Nq, self.num_heads, C // self.num_heads).permute(0, 2, 1, 3).contiguous()

        if self.sr_ratio > 1:
            tmp = torch.cat([kv, conf_kv], dim=-1)
            tmp_dict = kv_dict.copy()
            tmp_dict['x'] = tmp
            tmp_dict['map_size'] = q_dict['map_size']
            tmp = token2map(tmp_dict)

            kv = tmp[:, :C]
            conf_kv = tmp[:, C:]

            if self.use_sr_layer:
                kv = self.sr(kv)
                _, _, h, w = kv.shape
                kv = kv.reshape(B, C, -1).permute(0, 2, 1).contiguous()
                kv = self.norm(kv)
            else:
                kv = F.avg_pool2d(kv, kernel_size=self.sr_ratio, stride=self.sr_ratio)
                kv = kv.reshape(B, C, -1).permute(0, 2, 1).contiguous()

            conf_kv = F.avg_pool2d(conf_kv, kernel_size=self.sr_ratio, stride=self.sr_ratio)
            conf_kv = conf_kv.reshape(B, 1, -1).permute(0, 2, 1).contiguous()

        kv = self.kv(kv).reshape(B, -1, 2, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4).contiguous()
        k, v = kv[0], kv[1]

        attn = (q * self.scale) @ k.transpose(-2, -1)

        conf_kv = conf_kv.squeeze(-1)[:, None, None, :]
        attn = attn + conf_kv
        attn = attn.softmax(dim=-1)
        attn = self.attn_drop(attn)

        x = (attn @ v).transpose(1, 2).reshape(B, Nq, C)
        x = self.proj(x)
        x = self.proj_drop(x)
        return x


class TCBlock(nn.Module):
    """
    Transformer block for dynamic tokens.
    
    Args:
        dim: feature dimension
        num_heads: number of attention heads
        mlp_ratio: ratio of mlp hidden dim to embedding dim
        qkv_bias: whether to use bias for qkv projection
        qk_scale: scale factor for qk attention
        drop: dropout rate
        attn_drop: attention dropout rate
        drop_path: stochastic depth rate
        act_layer: activation layer
        norm_layer: normalization layer
        sr_ratio: spatial reduction ratio
        use_sr_layer: whether to use spatial reduction layer
    """
    def __init__(self, dim, num_heads, mlp_ratio=4., qkv_bias=True, qk_scale=None, 
                 drop=0., attn_drop=0., drop_path=0., act_layer=nn.GELU, 
                 norm_layer=nn.LayerNorm, sr_ratio=1, use_sr_layer=False):
        super().__init__()
        self.norm1 = norm_layer(dim)
        self.attn = TCAttention(
            dim,
            num_heads=num_heads, qkv_bias=qkv_bias, qk_scale=qk_scale,
            attn_drop=attn_drop, proj_drop=drop, sr_ratio=sr_ratio, use_sr_layer=use_sr_layer)
        # Drop path for stochastic depth
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.apply(self._init_weights)

    def _init_weights(self, m):
        """Initialize weights for the module."""
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()

    def forward(self, inputs):
        """
        Apply transformer block to token features.
        
        Args:
            inputs: single dictionary or tuple of dictionaries for 
                   query and key/value token information
            
        Returns:
            Updated query token dictionary
        """
        if isinstance(inputs, tuple) or isinstance(inputs, list):
            q_dict, kv_dict = inputs
        else:
            q_dict, kv_dict = inputs, None

        x = q_dict['x']
        # Apply normalization
        q_dict['x'] = self.norm1(q_dict['x'])
        if kv_dict is None:
            kv_dict = q_dict
        else:
            kv_dict['x'] = self.norm1(kv_dict['x'])

        # Apply attention
        x = x + self.drop_path(self.attn(q_dict, kv_dict))
        q_dict['x'] = x

        return q_dict